# Generated by Django 5.0.4 on 2024-12-10 06:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('documento', models.CharField(max_length=20)),
                ('tipo_evalua', models.CharField(choices=[('Evaluación', 'Evaluación'), ('Coevaluación', 'Coevaluación'), ('Autoevaluación', 'Autoevaluación')], max_length=20)),
                ('responsabilidad', models.IntegerField()),
                ('sentido_de_pertenencia', models.IntegerField()),
                ('trabajo_en_equipo', models.IntegerField()),
                ('liderazgo', models.IntegerField()),
                ('humanizacion', models.IntegerField()),
                ('seguridad', models.IntegerField()),
                ('observaciones', models.TextField()),
                ('promedio', models.FloatField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
